[sssd]
config_file_version = 2
services = nss, pam
# SSSD will not start if you do not configure any domains.
# Add new domain configurations as [domain/<NAME>] sections, and
# then add the list of domains (in the order you want them to be
# queried) to the "domains" attribute below and uncomment it.
domains = OURSPACEPLAYTHERAPY.CO.UK

[nss]

[pam]

[domain/OURSPACEPLAYTHERAPY.CO.UK]

cache_credentials = true

id_provider = ad
auth_provider = ad
access_provider = ad

ad_domain = OURSPACEPLAYTHERAPY.CO.UK

default_shell = /bin/sh
fallback_homedir = /home/%u
