# Global parameters
[global]
	dns forwarder = 192.168.1.254
	netbios name = DC
	realm = OURSPACEPLAYTHERAPY.CO.UK
	server role = active directory domain controller
	workgroup = OURSPACE
	idmap_ldb:use rfc2307 = yes
	disable netbios = yes
	interfaces = 192.168.1.4/32
	bind interfaces only = yes


[sysvol]
	path = /var/db/samba4/sysvol
	read only = No

[netlogon]
	path = /var/db/samba4/sysvol/ourspaceplaytherapy.co.uk/scripts
	read only = No
