# Global parameters
[global]
        workgroup = OURSPACE
        security = ads
        realm = OURSPACEPLAYTHERAPY.CO.UK
        kerberos method = secrets and keytab
        idmap config OURSPACEPLAYTHERAPY.CO.UK : backend = sss
        idmap config OURSPACEPLAYTHERAPY.CO.UK : range = 778400000-978400000
        idmap config * : backend = tdb
        idmap config * : range = 30000-40000
