---

- name: install and activate apache24
  hosts: elgar
  vars:
    srv: apache24
  become: true
  tasks:
  - name: install {{ srv }}
    pkgng:
      name: '{{ srv }} mod_php83 ap24-mod_authnz_external24 ap24-mod_authz_unixgroup24'
  - name: enable php and authz_external
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: wheel
      mode: '0644'
    loop:
      - { src: '../templates/apache24/modules.d/100_php.conf', dest: '/usr/local/etc/apache24/modules.d/100_php.conf' }
      - { src: '../templates/apache24/modules.d/101_authnz_external.conf', dest: '/usr/local/etc/apache24/modules.d/101_authnz_external.conf' }
  - name: make php ini file
    ansible.builtin.file:
      path: /usr/local/etc/php.ini
      src: /usr/local/etc/php.ini-production
      state: link
  - name: configure php
    ansible.builtin.lineinfile:
      path: /usr/local/etc/php.ini-production
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    loop:
      - { regexp: '^post_max_size', line: 'post_max_size = 500M' }
      - { regexp: '^upload_max_filesize', line: 'upload_max_filesize = 500M' }
      - { regexp: '^max_input_vars', line: 'max_input_vars = 100000' }
      - { regexp: '^memory_limit', line: 'memory_limit = 512M' }
      - { regexp: '^max_execution_time', line: 'max_execution_time = 500' }
      - { regexp: '^output_buffering', line: 'output_buffering = 0' }
      - { regexp: '^apc.enable_cli', line: 'apc.enable_cli = 1' }
      - { regexp: '^opcache.interned_strings_buffer', line: 'opcache.interned_strings_buffer = 32' }
  - name: add {{ srv }} runsv directory
    ansible.builtin.file:
      path: '/etc/sv/{{ srv }}'
      state: directory
      mode: '0755'
  - name: add {{ srv }} runsv file
    ansible.builtin.template:
      src: '../templates/runit/{{ srv }}_run'
      dest: '/etc/sv/{{ srv }}/run'
      owner: root
      group: wheel
      mode: '0755'
  - name: enable {{ srv }} boot
    ansible.builtin.file:
      src: '/etc/sv/{{ srv }}'
      dest: '/var/service/{{ srv }}'
      state: link
  - name: reload Apache
    community.general.runit:
      name: apache24
      state: reloaded
