---

- name: install and configure samba416
  hosts: dc
  become: true
  tasks:
  - name: install samba416
    pkgng:
      name: samba416
  - name: add samba runsv directory
    ansible.builtin.file:
      path: "/etc/sv/samba"
      state: directory
      mode: '0755'
  - name: add samba runsv file
    ansible.builtin.template:
      src: "../templates/runit/samba_run"
      dest: "/etc/sv/samba/run"
      owner: root
      group: wheel
      mode: '0755'
  - name: configure samba
    ansible.builtin.template:
      src: ../templates/smb4_dc.conf
      dest: /usr/local/etc/smb4.conf
      owner: root
      group: wheel
      mode: '0644'
    register: conf
  - name: check host-specific smb config file exists for {{ ansible_fqdn }}
    local_action: "stat path=../hostfiles/smb4_local.conf/{{ ansible_fqdn }}"
    register: smb4_local_conf
  - name: add host-specific smb config file if exists
    ansible.builtin.template:
      src: "../hostfiles/smb4_local.conf/{{ ansible_fqdn }}"
      dest: /usr/local/etc/smb4_local.conf
      owner: root
      group: wheel
      mode: '0644'
    when: smb4_local_conf.stat.exists
    register: local_conf
  - name: add samba db directory
    ansible.builtin.file:
      path: "/var/db/samba4"
      state: directory
      mode: '0755'
  - name: enable samba boot
    ansible.builtin.file:
      src: "/etc/sv/samba"
      dest: "/var/service/samba"
      state: link
  - name: reload samba
    community.general.runit:
      name: "samba"
      state: reloaded
      service_dir: /var/service
    when: local_conf.changed or conf.changed
