---

- name: install and activate syncthing
  hosts: none
  vars:
    srv: syncthing
  become: true
  tasks:
  - name: install {{ srv }}
    pkgng:
      name: '{{ srv }}'
  - name: add {{ srv }} runsv directory
    ansible.builtin.file:
      path: '/etc/sv/{{ srv }}'
      state: directory
      mode: '0755'
  - name: add {{ srv }} runsv file
    ansible.builtin.template:
      src: '../templates/runit/{{ srv }}_run'
      dest: '/etc/sv/{{ srv }}/run'
      owner: root
      group: wheel
      mode: '0755'
  - name: enable {{ srv }} boot
    ansible.builtin.file:
      src: '/etc/sv/{{ srv }}'
      dest: '/var/service/{{ srv }}'
      state: link
  - name: enable auth Apache
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: www
      group: www
      mode: '0600'
    loop:
      - { src: '../templates/apache24/modules.d/102_syncthing_proxy.conf', dest: '/usr/local/etc/apache24/modules.d/102_syncthing_proxy.conf' }
