---

- name: install and activate usermin
  hosts: elgar
  vars:
    srv: usermin
  become: true
  tasks:
  - name: install {{ srv }}
    pkgng:
      name: "{{ srv }}"
  - name: add {{ srv }} runsv directory
    ansible.builtin.file:
      path: '/etc/sv/{{ srv }}'
      state: directory
      mode: '0755'
  - name: add {{ srv }} runsv file
    ansible.builtin.template:
      src: '../templates/runit/{{ srv }}_run'
      dest: '/etc/sv/{{ srv }}/run'
      owner: root
      group: wheel
      mode: '0755'
  - name: enable {{ srv }} boot
    ansible.builtin.file:
      src: '/etc/sv/{{ srv }}'
      dest: '/var/service/{{ srv }}'
      state: link
  - name: enable {{ srv }} alias
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: wheel
      mode: '0644'
    loop:
      - { src: '../templates/apache24/modules.d/105_usermin.conf', dest: '/usr/local/etc/apache24/modules.d/105_usermin.conf' }
  - name: reload Apache
    community.general.runit:
      name: apache24
      state: reloaded
